[loggers]
keys=root,consolelogger

[handlers]
keys=consoleHandler

[formatters]
keys=sampleFormatter

[logger_root]
level=DEBUG
handlers=consoleHandler

[logger_consolelogger]
level=DEBUG
handlers=consoleHandler
qualname=consolelogger

[handler_consoleHandler]
class=StreamHandler
level=DEBUG
formatter=sampleFormatter

[formatter_sampleFormatter]
format=%(asctime)s:%(name)s:%(levelname)s:%(message)s
datefmt=%d/%m/%y %I:%M:%S %p
